function sanitizeTestTitle(text) {
  return String(text || '')
    .replace(/\s+/g, ' ')
    .replace(/['`]/g, '')
    .trim();
}

function asLiteral(value) {
  return JSON.stringify(value);
}

function pickIdentifier(rule, type) {
  const pathKey = `${type}Path`;
  const tagKey = `${type}Tag`;
  return rule[pathKey] || rule[tagKey] || null;
}

function buildDependencySpec(parsedForm) {
  const suiteName = sanitizeTestTitle(parsedForm.name || 'Generated logic tests');
  const dependencies = parsedForm.dependencies || [];

  const testBlocks = dependencies
    .map((rule, index) => {
      const trigger = pickIdentifier(rule, 'trigger');
      const target = pickIdentifier(rule, 'target');

      if (!trigger || !target) {
        const missing = [!trigger ? 'trigger' : null, !target ? 'target' : null].filter(Boolean).join(' and ');
        return `  it('dependency rule ${index + 1} has unresolved field identifiers', () => {\n    throw new Error('Generator could not resolve ${missing} identifier for dependency rule ${index + 1}.');\n  });`;
      }

      const name =
        sanitizeTestTitle(rule.description) ||
        `${target} visibility toggles from ${trigger}`;

      return `  it('${name}', () => {\n    cy.visit('/form-viewer.html?testMode=1&autoLoad=0');\n    cy.formViewerReady();\n\n    cy.fillField(${asLiteral(trigger)}, ${asLiteral(rule.hideValue)});\n    cy.expectHidden(${asLiteral(target)});\n\n    cy.fillField(${asLiteral(trigger)}, ${asLiteral(rule.showValue)});\n    cy.expectVisible(${asLiteral(target)});\n  });`;
    })
    .join('\n\n');

  return `describe('${suiteName} - autogenerated dependency tests', () => {\n${testBlocks || "  it('no dependencies discovered', () => {\n    cy.log('No dependency rules were discovered in this form definition.');\n  });"}\n});\n`;
}

module.exports = {
  buildDependencySpec
};
