function sanitizeTestTitle(text) {
  return String(text || '')
    .replace(/\s+/g, ' ')
    .replace(/['`]/g, '')
    .trim();
}

function asLiteral(value) {
  return JSON.stringify(value);
}

function pickIdentifier(rule, type) {
  const pathKey = `${type}Path`;
  const tagKey = `${type}Tag`;
  return rule[pathKey] || rule[tagKey] || null;
}

const CATEGORY_ALIASES = {
  logic: 'logic',
  dependencies: 'logic',
  'form-logic': 'logic',
  calculations: 'calculations',
  validations: 'validations',
  'required-fields': 'requiredFields',
  required: 'requiredFields',
  valueRanges: 'valueRanges',
  'value-ranges': 'valueRanges'
};

function normalizeCategories(categories) {
  if (!Array.isArray(categories) || categories.length === 0) {
    return ['logic'];
  }
  return [...new Set(categories.map((item) => CATEGORY_ALIASES[item] || item).filter(Boolean))];
}

function buildDependencyTests(parsedForm) {
  const dependencies = parsedForm.dependencies || [];

  return dependencies
    .map((rule, index) => {
      const trigger = pickIdentifier(rule, 'trigger');
      const target = pickIdentifier(rule, 'target');

      if (!trigger || !target) {
        const missing = [!trigger ? 'trigger' : null, !target ? 'target' : null].filter(Boolean).join(' and ');
        return `  it('dependency rule ${index + 1} has unresolved field identifiers', () => {\n    throw new Error('Generator could not resolve ${missing} identifier for dependency rule ${index + 1}.');\n  });`;
      }

      const name =
        sanitizeTestTitle(rule.description) ||
        `${target} visibility toggles from ${trigger}`;

      return `  it('${name}', () => {\n    cy.visit('/form-viewer.html?testMode=1&autoLoad=0');\n    cy.formViewerReady();\n\n    cy.fillField(${asLiteral(trigger)}, ${asLiteral(rule.hideValue)});\n    cy.expectHidden(${asLiteral(target)});\n\n    cy.fillField(${asLiteral(trigger)}, ${asLiteral(rule.showValue)});\n    cy.expectVisible(${asLiteral(target)});\n  });`;
    })
    .join('\n\n');
}

function buildSkippedCategoryTests(titlePrefix, rules, mapper) {
  return (rules || [])
    .map((rule, index) => {
      const title = sanitizeTestTitle(mapper(rule, index)) || `${titlePrefix} rule ${index + 1}`;
      return `  it.skip('${title}', () => {\n    cy.log('Autogenerated skeleton test. Add concrete input/output values before enabling this test.');\n  });`;
    })
    .join('\n\n');
}

function buildDependencySpec(parsedForm, options = {}) {
  const suiteName = sanitizeTestTitle(parsedForm.name || 'Generated logic tests');
  const selected = normalizeCategories(options.categories);
  const sections = [];

  if (selected.includes('logic')) {
    sections.push(buildDependencyTests(parsedForm));
  }

  if (selected.includes('calculations')) {
    sections.push(
      buildSkippedCategoryTests('calculation', parsedForm.calculations, (rule, index) =>
        rule?.field
          ? `calculation ${rule.field}${rule.expression ? ` uses ${sanitizeTestTitle(rule.expression)}` : ''}`
          : `calculation rule ${index + 1}`
      )
    );
  }

  if (selected.includes('validations')) {
    sections.push(
      buildSkippedCategoryTests('validation', parsedForm.validations, (rule) => {
        const limits = [rule?.min !== null ? `min ${rule.min}` : null, rule?.max !== null ? `max ${rule.max}` : null]
          .filter(Boolean)
          .join(', ');
        return `${rule?.field || 'field'} validation ${limits}`.trim();
      })
    );
  }

  if (selected.includes('valueRanges')) {
    sections.push(
      buildSkippedCategoryTests('value range', parsedForm.valueRanges, (rule) =>
        `${rule?.field || 'field'} value range (${rule?.min ?? '-∞'} to ${rule?.max ?? '+∞'})`
      )
    );
  }

  if (selected.includes('requiredFields')) {
    sections.push(
      buildSkippedCategoryTests('required field', parsedForm.requiredFields, (rule) =>
        `${rule?.field || 'field'} is required (min ${rule?.min ?? 1})`
      )
    );
  }

  const testBlocks = sections.filter(Boolean).join('\n\n');
  const fallback = "  it('no rules discovered for selected categories', () => {\n    cy.log('No rules were discovered in this form definition for the selected categories.');\n  });";

  return `describe('${suiteName} - autogenerated form tests', () => {\n${testBlocks || fallback}\n});\n`;
}

module.exports = {
  buildDependencySpec
};
