const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const JSZip = require('jszip');

const { parseFormDefinition } = require('./parser');
const { buildDependencySpec } = require('./generator');

const repoRoot = path.resolve(__dirname, '..');
const formZipFiles = [
  '24oktDemo_1_0_4_FORM.zip',
  'MDK_Lungcancer_1_0_329_FORM.zip',
  'MDK_Rek_demo_1_0_131_FORM.zip'
];

async function loadFormDescriptionFromBetterZip(zipPath) {
  const outerZip = await JSZip.loadAsync(fs.readFileSync(zipPath));
  const innerZipFileName = Object.keys(outerZip.files).find(
    (fileName) => fileName.toLowerCase().endsWith('.zip') && !outerZip.files[fileName].dir
  );

  assert.ok(innerZipFileName, `Expected nested form ZIP in ${path.basename(zipPath)}`);
  const innerZipBuffer = await outerZip.file(innerZipFileName).async('nodebuffer');
  const innerZip = await JSZip.loadAsync(innerZipBuffer);
  const formDescriptionText = await innerZip.file('form-description').async('string');
  return JSON.parse(formDescriptionText);
}

test('parser extracts dependency visibility rules from all bundled Better form ZIP examples', async () => {
  for (const fileName of formZipFiles) {
    const zipPath = path.join(repoRoot, 'src', 'example', 'forms', fileName);
    const formDescription = await loadFormDescriptionFromBetterZip(zipPath);
    const parsed = parseFormDefinition(formDescription);

    assert.equal(formDescription.rmType, 'FORM_DEFINITION');
    assert.ok(
      parsed.dependencies.length > 0,
      `Expected at least one dependency in parsed output for ${fileName}`
    );
  }
});

test('generator builds Cypress specs with expected command flow from parsed Better conditions', async () => {
  const zipPath = path.join(repoRoot, 'src', 'example', 'forms', formZipFiles[0]);
  const formDescription = await loadFormDescriptionFromBetterZip(zipPath);
  const parsed = parseFormDefinition(formDescription);
  const spec = buildDependencySpec(parsed);

  assert.match(spec, /cy\.visit\('\/form-viewer\.html\?testMode=1&autoLoad=0'\)/);
  assert.match(spec, /cy\.formViewerReady\(\)/);
  assert.match(spec, /cy\.expectHidden\(/);
  assert.match(spec, /cy\.expectVisible\(/);
});

test('CLI generates Cypress e2e output from a real Better form-description file', async () => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kintegrate-generator-test-'));
  const outFile = path.join(tmpDir, 'generated.cy.js');
  const inputFile = path.join(tmpDir, 'form-description.json');

  const zipPath = path.join(repoRoot, 'src', 'example', 'forms', formZipFiles[1]);
  const formDescription = await loadFormDescriptionFromBetterZip(zipPath);
  fs.writeFileSync(inputFile, JSON.stringify(formDescription), 'utf8');

  const cliResult = spawnSync(
    process.execPath,
    [path.join(repoRoot, 'test-generator', 'generate-cli.js'), '--form', inputFile, '--out', outFile],
    { encoding: 'utf8' }
  );

  assert.equal(cliResult.status, 0, cliResult.stderr || cliResult.stdout);
  assert.ok(fs.existsSync(outFile), 'Expected CLI to create output Cypress spec');

  const generated = fs.readFileSync(outFile, 'utf8');
  assert.match(generated, /autogenerated dependency tests/);
  assert.match(generated, /cy\.fillField\(/);
});
